//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelUnitTests.ServicioAlojamiento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Constantes", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Util")]
    public enum Constantes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Crear = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modificar = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eliminar = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Listar = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Obtener = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnioExpiraTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelUnitTests.ServicioAlojamiento.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodFormaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioCheckinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioCheckoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaHoraCheckinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaHoraCheckoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaLlegadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelUnitTests.ServicioAlojamiento.Habitacion HabitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MesExpiraTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Pasajero> PasajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequerimientosEspField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitularTarjetaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnioExpiraTarjeta {
            get {
                return this.AnioExpiraTarjetaField;
            }
            set {
                if ((this.AnioExpiraTarjetaField.Equals(value) != true)) {
                    this.AnioExpiraTarjetaField = value;
                    this.RaisePropertyChanged("AnioExpiraTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelUnitTests.ServicioAlojamiento.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodFormaPago {
            get {
                return this.CodFormaPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodFormaPagoField, value) != true)) {
                    this.CodFormaPagoField = value;
                    this.RaisePropertyChanged("CodFormaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComentarioCheckin {
            get {
                return this.ComentarioCheckinField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioCheckinField, value) != true)) {
                    this.ComentarioCheckinField = value;
                    this.RaisePropertyChanged("ComentarioCheckin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComentarioCheckout {
            get {
                return this.ComentarioCheckoutField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioCheckoutField, value) != true)) {
                    this.ComentarioCheckoutField = value;
                    this.RaisePropertyChanged("ComentarioCheckout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstadoCuenta {
            get {
                return this.EstadoCuentaField;
            }
            set {
                if ((this.EstadoCuentaField.Equals(value) != true)) {
                    this.EstadoCuentaField = value;
                    this.RaisePropertyChanged("EstadoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaHoraCheckin {
            get {
                return this.FechaHoraCheckinField;
            }
            set {
                if ((this.FechaHoraCheckinField.Equals(value) != true)) {
                    this.FechaHoraCheckinField = value;
                    this.RaisePropertyChanged("FechaHoraCheckin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaHoraCheckout {
            get {
                return this.FechaHoraCheckoutField;
            }
            set {
                if ((this.FechaHoraCheckoutField.Equals(value) != true)) {
                    this.FechaHoraCheckoutField = value;
                    this.RaisePropertyChanged("FechaHoraCheckout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaLlegada {
            get {
                return this.FechaLlegadaField;
            }
            set {
                if ((this.FechaLlegadaField.Equals(value) != true)) {
                    this.FechaLlegadaField = value;
                    this.RaisePropertyChanged("FechaLlegada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSalida {
            get {
                return this.FechaSalidaField;
            }
            set {
                if ((this.FechaSalidaField.Equals(value) != true)) {
                    this.FechaSalidaField = value;
                    this.RaisePropertyChanged("FechaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelUnitTests.ServicioAlojamiento.Habitacion Habitacion {
            get {
                return this.HabitacionField;
            }
            set {
                if ((object.ReferenceEquals(this.HabitacionField, value) != true)) {
                    this.HabitacionField = value;
                    this.RaisePropertyChanged("Habitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReserva {
            get {
                return this.IdReservaField;
            }
            set {
                if ((this.IdReservaField.Equals(value) != true)) {
                    this.IdReservaField = value;
                    this.RaisePropertyChanged("IdReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MesExpiraTarjeta {
            get {
                return this.MesExpiraTarjetaField;
            }
            set {
                if ((this.MesExpiraTarjetaField.Equals(value) != true)) {
                    this.MesExpiraTarjetaField = value;
                    this.RaisePropertyChanged("MesExpiraTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTarjeta {
            get {
                return this.NumeroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTarjetaField, value) != true)) {
                    this.NumeroTarjetaField = value;
                    this.RaisePropertyChanged("NumeroTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Pasajero> Pasajero {
            get {
                return this.PasajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroField, value) != true)) {
                    this.PasajeroField = value;
                    this.RaisePropertyChanged("Pasajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequerimientosEsp {
            get {
                return this.RequerimientosEspField;
            }
            set {
                if ((object.ReferenceEquals(this.RequerimientosEspField, value) != true)) {
                    this.RequerimientosEspField = value;
                    this.RaisePropertyChanged("RequerimientosEsp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitularTarjeta {
            get {
                return this.TitularTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.TitularTarjetaField, value) != true)) {
                    this.TitularTarjetaField = value;
                    this.RaisePropertyChanged("TitularTarjeta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelUnitTests.ServicioAlojamiento.Pais PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelUnitTests.ServicioAlojamiento.TipoDocumento TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelUnitTests.ServicioAlojamiento.Pais Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelUnitTests.ServicioAlojamiento.TipoDocumento TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Habitacion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Habitacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdHabitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelUnitTests.ServicioAlojamiento.TipoHabitacion TipoHabitacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdHabitacion {
            get {
                return this.IdHabitacionField;
            }
            set {
                if ((this.IdHabitacionField.Equals(value) != true)) {
                    this.IdHabitacionField = value;
                    this.RaisePropertyChanged("IdHabitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Piso {
            get {
                return this.PisoField;
            }
            set {
                if ((this.PisoField.Equals(value) != true)) {
                    this.PisoField = value;
                    this.RaisePropertyChanged("Piso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelUnitTests.ServicioAlojamiento.TipoHabitacion TipoHabitacion {
            get {
                return this.TipoHabitacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoHabitacionField, value) != true)) {
                    this.TipoHabitacionField = value;
                    this.RaisePropertyChanged("TipoHabitacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pasajero", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Pasajero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPasajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePasajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelUnitTests.ServicioAlojamiento.Reserva ReservaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPasajero {
            get {
                return this.IdPasajeroField;
            }
            set {
                if ((this.IdPasajeroField.Equals(value) != true)) {
                    this.IdPasajeroField = value;
                    this.RaisePropertyChanged("IdPasajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePasajero {
            get {
                return this.NombrePasajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePasajeroField, value) != true)) {
                    this.NombrePasajeroField = value;
                    this.RaisePropertyChanged("NombrePasajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelUnitTests.ServicioAlojamiento.Reserva Reserva {
            get {
                return this.ReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservaField, value) != true)) {
                    this.ReservaField = value;
                    this.RaisePropertyChanged("Reserva");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pais", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Pais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((this.IdPaisField.Equals(value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePais {
            get {
                return this.NombrePaisField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePaisField, value) != true)) {
                    this.NombrePaisField = value;
                    this.RaisePropertyChanged("NombrePais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumento", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class TipoDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumento {
            get {
                return this.IdTipoDocumentoField;
            }
            set {
                if ((this.IdTipoDocumentoField.Equals(value) != true)) {
                    this.IdTipoDocumentoField = value;
                    this.RaisePropertyChanged("IdTipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoHabitacion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class TipoHabitacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoHabitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TarifaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoHabitacion {
            get {
                return this.IdTipoHabitacionField;
            }
            set {
                if ((this.IdTipoHabitacionField.Equals(value) != true)) {
                    this.IdTipoHabitacionField = value;
                    this.RaisePropertyChanged("IdTipoHabitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tarifa {
            get {
                return this.TarifaField;
            }
            set {
                if ((this.TarifaField.Equals(value) != true)) {
                    this.TarifaField = value;
                    this.RaisePropertyChanged("Tarifa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAlojamiento.IAlojamiento")]
    public interface IAlojamiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/ReservarHabitacion", ReplyAction="http://tempuri.org/IAlojamiento/ReservarHabitacionResponse")]
        System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva> ReservarHabitacion(HotelUnitTests.ServicioAlojamiento.Constantes valor, HotelUnitTests.ServicioAlojamiento.Reserva reserva, int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/ReservarHabitacion", ReplyAction="http://tempuri.org/IAlojamiento/ReservarHabitacionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva>> ReservarHabitacionAsync(HotelUnitTests.ServicioAlojamiento.Constantes valor, HotelUnitTests.ServicioAlojamiento.Reserva reserva, int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/RegistrarCheckin", ReplyAction="http://tempuri.org/IAlojamiento/RegistrarCheckinResponse")]
        System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva> RegistrarCheckin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/RegistrarCheckin", ReplyAction="http://tempuri.org/IAlojamiento/RegistrarCheckinResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva>> RegistrarCheckinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/RegistrarCheckout", ReplyAction="http://tempuri.org/IAlojamiento/RegistrarCheckoutResponse")]
        System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva> RegistrarCheckout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/RegistrarCheckout", ReplyAction="http://tempuri.org/IAlojamiento/RegistrarCheckoutResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva>> RegistrarCheckoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/CancelarReserva", ReplyAction="http://tempuri.org/IAlojamiento/CancelarReservaResponse")]
        void CancelarReserva();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/CancelarReserva", ReplyAction="http://tempuri.org/IAlojamiento/CancelarReservaResponse")]
        System.Threading.Tasks.Task CancelarReservaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/ValidarCancelacion", ReplyAction="http://tempuri.org/IAlojamiento/ValidarCancelacionResponse")]
        bool ValidarCancelacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/ValidarCancelacion", ReplyAction="http://tempuri.org/IAlojamiento/ValidarCancelacionResponse")]
        System.Threading.Tasks.Task<bool> ValidarCancelacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/ObtenerReserva", ReplyAction="http://tempuri.org/IAlojamiento/ObtenerReservaResponse")]
        System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva> ObtenerReserva(int codigo, string fechaChekIndel, string fechaChekInAl, string fechaChekOutdel, string fechaChekOutal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlojamiento/ObtenerReserva", ReplyAction="http://tempuri.org/IAlojamiento/ObtenerReservaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva>> ObtenerReservaAsync(int codigo, string fechaChekIndel, string fechaChekInAl, string fechaChekOutdel, string fechaChekOutal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlojamientoChannel : HotelUnitTests.ServicioAlojamiento.IAlojamiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlojamientoClient : System.ServiceModel.ClientBase<HotelUnitTests.ServicioAlojamiento.IAlojamiento>, HotelUnitTests.ServicioAlojamiento.IAlojamiento {
        
        public AlojamientoClient() {
        }
        
        public AlojamientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlojamientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlojamientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlojamientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva> ReservarHabitacion(HotelUnitTests.ServicioAlojamiento.Constantes valor, HotelUnitTests.ServicioAlojamiento.Reserva reserva, int codigo) {
            return base.Channel.ReservarHabitacion(valor, reserva, codigo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva>> ReservarHabitacionAsync(HotelUnitTests.ServicioAlojamiento.Constantes valor, HotelUnitTests.ServicioAlojamiento.Reserva reserva, int codigo) {
            return base.Channel.ReservarHabitacionAsync(valor, reserva, codigo);
        }
        
        public System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva> RegistrarCheckin() {
            return base.Channel.RegistrarCheckin();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva>> RegistrarCheckinAsync() {
            return base.Channel.RegistrarCheckinAsync();
        }
        
        public System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva> RegistrarCheckout() {
            return base.Channel.RegistrarCheckout();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva>> RegistrarCheckoutAsync() {
            return base.Channel.RegistrarCheckoutAsync();
        }
        
        public void CancelarReserva() {
            base.Channel.CancelarReserva();
        }
        
        public System.Threading.Tasks.Task CancelarReservaAsync() {
            return base.Channel.CancelarReservaAsync();
        }
        
        public bool ValidarCancelacion() {
            return base.Channel.ValidarCancelacion();
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCancelacionAsync() {
            return base.Channel.ValidarCancelacionAsync();
        }
        
        public System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva> ObtenerReserva(int codigo, string fechaChekIndel, string fechaChekInAl, string fechaChekOutdel, string fechaChekOutal) {
            return base.Channel.ObtenerReserva(codigo, fechaChekIndel, fechaChekInAl, fechaChekOutdel, fechaChekOutal);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HotelUnitTests.ServicioAlojamiento.Reserva>> ObtenerReservaAsync(int codigo, string fechaChekIndel, string fechaChekInAl, string fechaChekOutdel, string fechaChekOutal) {
            return base.Channel.ObtenerReservaAsync(codigo, fechaChekIndel, fechaChekInAl, fechaChekOutdel, fechaChekOutal);
        }
    }
}
