//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosHoteles.ServicioCuenta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostoUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiciosHoteles.ServicioCuenta.Reserva ReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiciosHoteles.ServicioCuenta.Servicio ServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CostoUnitario {
            get {
                return this.CostoUnitarioField;
            }
            set {
                if ((this.CostoUnitarioField.Equals(value) != true)) {
                    this.CostoUnitarioField = value;
                    this.RaisePropertyChanged("CostoUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCuenta {
            get {
                return this.IdCuentaField;
            }
            set {
                if ((this.IdCuentaField.Equals(value) != true)) {
                    this.IdCuentaField = value;
                    this.RaisePropertyChanged("IdCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosHoteles.ServicioCuenta.Reserva Reserva {
            get {
                return this.ReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservaField, value) != true)) {
                    this.ReservaField = value;
                    this.RaisePropertyChanged("Reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosHoteles.ServicioCuenta.Servicio Servicio {
            get {
                return this.ServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicioField, value) != true)) {
                    this.ServicioField = value;
                    this.RaisePropertyChanged("Servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnioExpiraTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiciosHoteles.ServicioCuenta.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodFormaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioCheckinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioCheckoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaHoraCheckinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaHoraCheckoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaLlegadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiciosHoteles.ServicioCuenta.Habitacion HabitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MesExpiraTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiciosHoteles.ServicioCuenta.Pasajero[] PasajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequerimientosEspField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitularTarjetaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnioExpiraTarjeta {
            get {
                return this.AnioExpiraTarjetaField;
            }
            set {
                if ((this.AnioExpiraTarjetaField.Equals(value) != true)) {
                    this.AnioExpiraTarjetaField = value;
                    this.RaisePropertyChanged("AnioExpiraTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosHoteles.ServicioCuenta.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodFormaPago {
            get {
                return this.CodFormaPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodFormaPagoField, value) != true)) {
                    this.CodFormaPagoField = value;
                    this.RaisePropertyChanged("CodFormaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComentarioCheckin {
            get {
                return this.ComentarioCheckinField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioCheckinField, value) != true)) {
                    this.ComentarioCheckinField = value;
                    this.RaisePropertyChanged("ComentarioCheckin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComentarioCheckout {
            get {
                return this.ComentarioCheckoutField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioCheckoutField, value) != true)) {
                    this.ComentarioCheckoutField = value;
                    this.RaisePropertyChanged("ComentarioCheckout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstadoCuenta {
            get {
                return this.EstadoCuentaField;
            }
            set {
                if ((this.EstadoCuentaField.Equals(value) != true)) {
                    this.EstadoCuentaField = value;
                    this.RaisePropertyChanged("EstadoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaHoraCheckin {
            get {
                return this.FechaHoraCheckinField;
            }
            set {
                if ((this.FechaHoraCheckinField.Equals(value) != true)) {
                    this.FechaHoraCheckinField = value;
                    this.RaisePropertyChanged("FechaHoraCheckin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaHoraCheckout {
            get {
                return this.FechaHoraCheckoutField;
            }
            set {
                if ((this.FechaHoraCheckoutField.Equals(value) != true)) {
                    this.FechaHoraCheckoutField = value;
                    this.RaisePropertyChanged("FechaHoraCheckout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaLlegada {
            get {
                return this.FechaLlegadaField;
            }
            set {
                if ((this.FechaLlegadaField.Equals(value) != true)) {
                    this.FechaLlegadaField = value;
                    this.RaisePropertyChanged("FechaLlegada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSalida {
            get {
                return this.FechaSalidaField;
            }
            set {
                if ((this.FechaSalidaField.Equals(value) != true)) {
                    this.FechaSalidaField = value;
                    this.RaisePropertyChanged("FechaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosHoteles.ServicioCuenta.Habitacion Habitacion {
            get {
                return this.HabitacionField;
            }
            set {
                if ((object.ReferenceEquals(this.HabitacionField, value) != true)) {
                    this.HabitacionField = value;
                    this.RaisePropertyChanged("Habitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReserva {
            get {
                return this.IdReservaField;
            }
            set {
                if ((this.IdReservaField.Equals(value) != true)) {
                    this.IdReservaField = value;
                    this.RaisePropertyChanged("IdReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MesExpiraTarjeta {
            get {
                return this.MesExpiraTarjetaField;
            }
            set {
                if ((this.MesExpiraTarjetaField.Equals(value) != true)) {
                    this.MesExpiraTarjetaField = value;
                    this.RaisePropertyChanged("MesExpiraTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTarjeta {
            get {
                return this.NumeroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTarjetaField, value) != true)) {
                    this.NumeroTarjetaField = value;
                    this.RaisePropertyChanged("NumeroTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosHoteles.ServicioCuenta.Pasajero[] Pasajero {
            get {
                return this.PasajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroField, value) != true)) {
                    this.PasajeroField = value;
                    this.RaisePropertyChanged("Pasajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequerimientosEsp {
            get {
                return this.RequerimientosEspField;
            }
            set {
                if ((object.ReferenceEquals(this.RequerimientosEspField, value) != true)) {
                    this.RequerimientosEspField = value;
                    this.RaisePropertyChanged("RequerimientosEsp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitularTarjeta {
            get {
                return this.TitularTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.TitularTarjetaField, value) != true)) {
                    this.TitularTarjetaField = value;
                    this.RaisePropertyChanged("TitularTarjeta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servicio", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Servicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TarifaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdServicio {
            get {
                return this.IdServicioField;
            }
            set {
                if ((this.IdServicioField.Equals(value) != true)) {
                    this.IdServicioField = value;
                    this.RaisePropertyChanged("IdServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tarifa {
            get {
                return this.TarifaField;
            }
            set {
                if ((this.TarifaField.Equals(value) != true)) {
                    this.TarifaField = value;
                    this.RaisePropertyChanged("Tarifa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiciosHoteles.ServicioCuenta.Pais PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiciosHoteles.ServicioCuenta.TipoDocumento TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosHoteles.ServicioCuenta.Pais Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosHoteles.ServicioCuenta.TipoDocumento TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Habitacion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Habitacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdHabitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiciosHoteles.ServicioCuenta.TipoHabitacion TipoHabitacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdHabitacion {
            get {
                return this.IdHabitacionField;
            }
            set {
                if ((this.IdHabitacionField.Equals(value) != true)) {
                    this.IdHabitacionField = value;
                    this.RaisePropertyChanged("IdHabitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Piso {
            get {
                return this.PisoField;
            }
            set {
                if ((this.PisoField.Equals(value) != true)) {
                    this.PisoField = value;
                    this.RaisePropertyChanged("Piso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosHoteles.ServicioCuenta.TipoHabitacion TipoHabitacion {
            get {
                return this.TipoHabitacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoHabitacionField, value) != true)) {
                    this.TipoHabitacionField = value;
                    this.RaisePropertyChanged("TipoHabitacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pasajero", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Pasajero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPasajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePasajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiciosHoteles.ServicioCuenta.Reserva ReservaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPasajero {
            get {
                return this.IdPasajeroField;
            }
            set {
                if ((this.IdPasajeroField.Equals(value) != true)) {
                    this.IdPasajeroField = value;
                    this.RaisePropertyChanged("IdPasajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePasajero {
            get {
                return this.NombrePasajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePasajeroField, value) != true)) {
                    this.NombrePasajeroField = value;
                    this.RaisePropertyChanged("NombrePasajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosHoteles.ServicioCuenta.Reserva Reserva {
            get {
                return this.ReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservaField, value) != true)) {
                    this.ReservaField = value;
                    this.RaisePropertyChanged("Reserva");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pais", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Pais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((this.IdPaisField.Equals(value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePais {
            get {
                return this.NombrePaisField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePaisField, value) != true)) {
                    this.NombrePaisField = value;
                    this.RaisePropertyChanged("NombrePais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumento", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class TipoDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumento {
            get {
                return this.IdTipoDocumentoField;
            }
            set {
                if ((this.IdTipoDocumentoField.Equals(value) != true)) {
                    this.IdTipoDocumentoField = value;
                    this.RaisePropertyChanged("IdTipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoHabitacion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class TipoHabitacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoHabitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TarifaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoHabitacion {
            get {
                return this.IdTipoHabitacionField;
            }
            set {
                if ((this.IdTipoHabitacionField.Equals(value) != true)) {
                    this.IdTipoHabitacionField = value;
                    this.RaisePropertyChanged("IdTipoHabitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tarifa {
            get {
                return this.TarifaField;
            }
            set {
                if ((this.TarifaField.Equals(value) != true)) {
                    this.TarifaField = value;
                    this.RaisePropertyChanged("Tarifa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCuenta.ICuentas")]
    public interface ICuentas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentas/CrearCuenta", ReplyAction="http://tempuri.org/ICuentas/CrearCuentaResponse")]
        ServiciosHoteles.ServicioCuenta.Cuenta CrearCuenta(ServiciosHoteles.ServicioCuenta.Cuenta cuentaNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentas/CrearCuenta", ReplyAction="http://tempuri.org/ICuentas/CrearCuentaResponse")]
        System.Threading.Tasks.Task<ServiciosHoteles.ServicioCuenta.Cuenta> CrearCuentaAsync(ServiciosHoteles.ServicioCuenta.Cuenta cuentaNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentas/ModificarCuenta", ReplyAction="http://tempuri.org/ICuentas/ModificarCuentaResponse")]
        ServiciosHoteles.ServicioCuenta.Cuenta ModificarCuenta(ServiciosHoteles.ServicioCuenta.Cuenta cuentaModificada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentas/ModificarCuenta", ReplyAction="http://tempuri.org/ICuentas/ModificarCuentaResponse")]
        System.Threading.Tasks.Task<ServiciosHoteles.ServicioCuenta.Cuenta> ModificarCuentaAsync(ServiciosHoteles.ServicioCuenta.Cuenta cuentaModificada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentas/EliminarCuenta", ReplyAction="http://tempuri.org/ICuentas/EliminarCuentaResponse")]
        void EliminarCuenta(ServiciosHoteles.ServicioCuenta.Cuenta cuentaEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentas/EliminarCuenta", ReplyAction="http://tempuri.org/ICuentas/EliminarCuentaResponse")]
        System.Threading.Tasks.Task EliminarCuentaAsync(ServiciosHoteles.ServicioCuenta.Cuenta cuentaEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentas/ObtenerCuenta", ReplyAction="http://tempuri.org/ICuentas/ObtenerCuentaResponse")]
        ServiciosHoteles.ServicioCuenta.Cuenta ObtenerCuenta(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentas/ObtenerCuenta", ReplyAction="http://tempuri.org/ICuentas/ObtenerCuentaResponse")]
        System.Threading.Tasks.Task<ServiciosHoteles.ServicioCuenta.Cuenta> ObtenerCuentaAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentas/ListarCuentas", ReplyAction="http://tempuri.org/ICuentas/ListarCuentasResponse")]
        ServiciosHoteles.ServicioCuenta.Cuenta[] ListarCuentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentas/ListarCuentas", ReplyAction="http://tempuri.org/ICuentas/ListarCuentasResponse")]
        System.Threading.Tasks.Task<ServiciosHoteles.ServicioCuenta.Cuenta[]> ListarCuentasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICuentasChannel : ServiciosHoteles.ServicioCuenta.ICuentas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuentasClient : System.ServiceModel.ClientBase<ServiciosHoteles.ServicioCuenta.ICuentas>, ServiciosHoteles.ServicioCuenta.ICuentas {
        
        public CuentasClient() {
        }
        
        public CuentasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuentasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiciosHoteles.ServicioCuenta.Cuenta CrearCuenta(ServiciosHoteles.ServicioCuenta.Cuenta cuentaNueva) {
            return base.Channel.CrearCuenta(cuentaNueva);
        }
        
        public System.Threading.Tasks.Task<ServiciosHoteles.ServicioCuenta.Cuenta> CrearCuentaAsync(ServiciosHoteles.ServicioCuenta.Cuenta cuentaNueva) {
            return base.Channel.CrearCuentaAsync(cuentaNueva);
        }
        
        public ServiciosHoteles.ServicioCuenta.Cuenta ModificarCuenta(ServiciosHoteles.ServicioCuenta.Cuenta cuentaModificada) {
            return base.Channel.ModificarCuenta(cuentaModificada);
        }
        
        public System.Threading.Tasks.Task<ServiciosHoteles.ServicioCuenta.Cuenta> ModificarCuentaAsync(ServiciosHoteles.ServicioCuenta.Cuenta cuentaModificada) {
            return base.Channel.ModificarCuentaAsync(cuentaModificada);
        }
        
        public void EliminarCuenta(ServiciosHoteles.ServicioCuenta.Cuenta cuentaEliminar) {
            base.Channel.EliminarCuenta(cuentaEliminar);
        }
        
        public System.Threading.Tasks.Task EliminarCuentaAsync(ServiciosHoteles.ServicioCuenta.Cuenta cuentaEliminar) {
            return base.Channel.EliminarCuentaAsync(cuentaEliminar);
        }
        
        public ServiciosHoteles.ServicioCuenta.Cuenta ObtenerCuenta(int codigo) {
            return base.Channel.ObtenerCuenta(codigo);
        }
        
        public System.Threading.Tasks.Task<ServiciosHoteles.ServicioCuenta.Cuenta> ObtenerCuentaAsync(int codigo) {
            return base.Channel.ObtenerCuentaAsync(codigo);
        }
        
        public ServiciosHoteles.ServicioCuenta.Cuenta[] ListarCuentas() {
            return base.Channel.ListarCuentas();
        }
        
        public System.Threading.Tasks.Task<ServiciosHoteles.ServicioCuenta.Cuenta[]> ListarCuentasAsync() {
            return base.Channel.ListarCuentasAsync();
        }
    }
}
